DELETE http://localhost:3003/api/blogs/664a550854eb2e939278aa2c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2NjRhNTRkYWZiYWFhM2FlNDNiZmI1NTAiLCJpYXQiOjE3MTYyMTQ4ODksImV4cCI6MTcxNjIxODQ4OX0.8Q8wRMCkqtQL8LmlaPUVKYvUYnV4kj9mwn2QdXddNm4
