POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2hhcmQiLCJpZCI6IjY2NDBkMWFhNjljZmY5ZDY5MjAxMjZmNyIsImlhdCI6MTcxNTYxMjkzNn0.oYRDIOO24vE9SForBNnSBQ-VAZEUwMrQa8pVNkps5Cw

{
  "title": "3",
  "author": "A Author",
  "url": "https://richard.com",
  "likes": 5
}
